export enum ResultMesagge{
    NO_ES_ARBOL = "NO ES UN ARBOL",
    PROBLEMA_STORAGE_SERVICE = "PROBLEMA CON STORAGE SERVICE",
    PROBLEMA_EN_BASE_DE_DATOS= "PROBLEMA AL GUARDAR EN BASE DE DATOS",
    EXITO = "EL ARBOL SE HA GUARDADO CORRECTAMENTE"
}